// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Q040cB-INJVnPFpk6TaSBXfTnevNtrI',
    appId: '1:417581692669:web:13d2c6d1bf7f4e58027094',
    messagingSenderId: '417581692669',
    projectId: 'bookfinder-f2915',
    authDomain: 'bookfinder-f2915.firebaseapp.com',
    storageBucket: 'bookfinder-f2915.firebasestorage.app',
    measurementId: 'G-QPCL7V3230',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeDRGgZ4tuwqxPPcAMQYQLbFRoNLOpKF8',
    appId: '1:417581692669:android:536690b3b9646be5027094',
    messagingSenderId: '417581692669',
    projectId: 'bookfinder-f2915',
    storageBucket: 'bookfinder-f2915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGHRW19vwu7PMcEwAUSIxpcHBGnFsWQE',
    appId: '1:417581692669:ios:8219eb7e2c98df0b027094',
    messagingSenderId: '417581692669',
    projectId: 'bookfinder-f2915',
    storageBucket: 'bookfinder-f2915.firebasestorage.app',
    iosBundleId: 'com.example.bookFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeGHRW19vwu7PMcEwAUSIxpcHBGnFsWQE',
    appId: '1:417581692669:ios:8219eb7e2c98df0b027094',
    messagingSenderId: '417581692669',
    projectId: 'bookfinder-f2915',
    storageBucket: 'bookfinder-f2915.firebasestorage.app',
    iosBundleId: 'com.example.bookFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Q040cB-INJVnPFpk6TaSBXfTnevNtrI',
    appId: '1:417581692669:web:91327bbbd8ae5824027094',
    messagingSenderId: '417581692669',
    projectId: 'bookfinder-f2915',
    authDomain: 'bookfinder-f2915.firebaseapp.com',
    storageBucket: 'bookfinder-f2915.firebasestorage.app',
    measurementId: 'G-8QNMX1HEXD',
  );
}
